import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  es: {
    translation: {
      "carouselPrincipal1": "Encuentra la oficina de tus sueños en un solo lugar",
      "carouselPrincipal2": "Espacio dedicados y profesionales",
      "carouselPrincipal3": "Mayor productividad y enfoque al trabajar",
      "carouselPrincipal4": "Colaboración y comunicación",
      "carouselPrincipal5": "Imagen y profesionalismo",
      "title1": "Prueba Nuestro Mapa Interactivo",
      "subtitle1": "Tu espacio de éxito, la oficina perfecta.",
      "subtitle2": "Transforma tu visión en realidad, en nuestra oficina ideal.",
      "title2": "¿Necesitas una oficina?",
      "p1": "Nuestra empresa ofrece oficinas de alquiler flexibles diseñadas para satisfacer todas tus necesidades empresariales. ¡No pierdas más tiempo buscando, ven a experimentar el futuro del trabajo con nosotros hoy mismo!",
      "carouselCards1": "Flexibilidad sin compromisos: Alquiler a medida, sin ataduras a largo plazo.",
      "carouselCards2": "Infraestructura de calidad: Oficinas modernas y completamente equipadas.",
      "carouselCards3": "Ubicaciones estratégicas: Acceso conveniente a centros empresariales y transporte.",
      "title3": "Encuentra mas oficinas",
      "buttonAllOffices": "Ver mas",
      "title4": "¿Por que buscar con nosotros?",
      "p2": "Nuestra empresa ofrece una experiencia única, pensando en tu comodidad y productividad. Disfrutarás de la máxima flexibilidad en términos de duración de alquiler, sin preocupaciones por compromisos a largo plazo. Nuestras oficinas están completamente equipadas con una moderna infraestructura y todas las comodidades que necesitas para impulsar tu rendimiento.",
      "login": "Inicio de sesión",
      "email": "Correo",
      "password": "Contraseña",
      "buttonLogin": "Ingresar",
      "linkRegister1": "¿No tienes una cuenta?",
      "linkRegister2": "¡Registrate!",
      "register": "Registro",
      "name": "Nombre",
      "email1": "Correo",
      "password1": "Contraseña",
      "repeatPassword": "Repetir Contraseña",
      "buttonRegister": "Registrarse",
      "linkLogin1": "¿Ya tienes una cuenta?",
      "linkLogin2": "¡Inicia Sesión!",
      "profile": "Perfil",
      "data": "Datos",
      "reservation": "Reservaciones",
      "offices":"Oficinas",
      "admin":"Administrador",
      "logout": "Cerrar Sesión",
      "image": "Imagen",
      "titleModal": "Titulo de la oficina",
      "description": "Descripcion",
      "price": "Precio",
      "capacity": "Capacidad",
      "direction": "Dirección",
      "ubication": "Ubicación",
      "buttonUpdate": "Editar",
      "buttonAdd": "Agregar Oficina",
      "officesNotFound": "No se encontraron Oficinas disponibles en este momento.",
      "confirmDelete": "¿Está seguro/a de eliminar esta",
      "buttonDelete1": "Volver atrás",
      "buttonDelete2": "Eliminar",
      "priceOffice": "Precio de alquiler",
      "allOffices": "Todas las oficinas",
      "reservationNotFound": "No se encontraron Resrvaciones disponibles en este momento.",
      "menu": "Menu",
      "sectionAdmin": "Sección Administrativa",
      "statistics": "Estadísticas",
      "users": "Usuarios",
      "browse": "Navegar",
      "start": "Inicio",
      "adminPanel": "Panel de Administración",
      "error404": "Página no encontrada",
      "error404-2": "Lo sentimos, no pudimos encontrar la página que estas buscando.",
      "buttonBackStart": "Regresar al inicio",
      "contact": "Contacto",
      "socialMedia": "Redes Sociales",
      "developers": "Desarrolladores",
      "copyright": ". Todos los derechos reservados.",
      
    }
  },
  en: {
    translation: {
      "carouselPrincipal1": "Find the office of your dreams in one place",
      "carouselPrincipal2": "Dedicated and professional space",
      "carouselPrincipal3": "Increased productivity and focus at work",
      "carouselPrincipal4": "Collaboration and communication",
      "carouselPrincipal5": "Image and professionalism",
      "title1": "Try Our Interactive Map",
      "subtitle1": "Your successful space, the perfect office.",
      "subtitle2": "Transform your vision into reality, in our ideal office.",
      "title2": "Do you need an office?",
      "p1": "Our company offers flexible rental offices designed to meet all your business needs. Waste no more time searching, come experience the future of work with us today!",
      "carouselCards1": "Flexibility without compromise: Tailor-made rental, no long-term strings attached.",
      "carouselCards2": "Quality infrastructure: Modern and fully equipped offices.",
      "carouselCards3": "Strategic locations: Convenient access to business centers and transportation.",
      "title3": "Find more offices",
      "buttonAllOffices": "See more",
      "title4": "Why search with us?",
      "p2": "Our company offers a unique experience, thinking about your comfort and productivity. You'll enjoy maximum flexibility in terms of rental length, without worrying about long-term commitments. Our offices are fully equipped with a modern infrastructure and all the comforts you need to boost your performance.",
      "login": "Login",
      "email": "Email",
      "password": "Password",
      "buttonLogin": "Get into",
      "linkRegister1": "You do not have an account?",
      "linkRegister2": "Sign up!",
      "register": "Registro",
      "name": "Name",
      "email1": "Email",
      "password1": "Password",
      "repeatPassword": "Repeat Password",
      "buttonRegister": "Check in",
      "linkLogin1": "Do you already have an account?",
      "linkLogin2": "Log in!",
      "profile": "Profile",
      "data": "Data",
      "reservation": "Reservation",
      "offices":"Offices",
      "admin":"Administrator",
      "logout": "Sign off",
      "image": "Image",
      "titleModal": "Office title",
      "description": "Description",
      "price": "Price",
      "capacity": "Capacity",
      "direction": "Direction",
      "ubication": "Ubication",
      "buttonUpdate": "Edit",
      "buttonAdd": "Add Office",
      "officesNotFond": "No Offices available at this time.",
      "confirmDelete": "Are you sure to delete this",
      "buttonDelete1": "Go back",
      "buttonDelete2": "Delete",
      "priceOffice": "Rental price",
      "allOffices": "All offices",
      "reservationNotFound": "No Reservations available at this time.",
      "menu": "Menu",
      "sectionAdmin": "Administrative Section",
      "statistics": "Statistics",
      "users": "Users",
      "browse": "Browse",
      "start": "Start",
      "adminPanel": "Administration panel",
      "error404": "Page not found",
      "error404-2": "Sorry, we couldn't find the page you're looking for.",
      "buttonBackStart": "Back to start",
      "contact": "Contact",
      "socialMedia": "Social Media",
      "developers": "Developers",
      "copyright": ". All rights reserved.",
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "es",
    interpolation: {
      escapeValue: false
    }
  });

  export default i18n;